#!/usr/bin/env groovy
pipeline {
    agent none
    stages {
        stage('Build') {
            agent {
                    docker {
                      image 'maven:3-alpine'
                      label 'my-defined-label'
                      args  '-v /tmp:/tmp'
                  }
            }
            steps {
                sh "mvn package -Dmaven.test.skip=true"
            }
        }
    }
}
